# Generated by Django 5.1.6 on 2025-04-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Text displayed for the form field.', max_length=255)),
                ('field_name', models.SlugField(help_text="Internal name for the field (no spaces, e.g., 'first_name').", max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text (Single Line)'), ('textarea', 'Text Area (Multi Line)'), ('email', 'Email'), ('number', 'Number'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('date', 'Date')], max_length=20)),
                ('help_text', models.CharField(blank=True, help_text='Optional help text displayed with the field.', max_length=255)),
                ('choices', models.TextField(blank=True, help_text="For 'select' or 'radio' types, enter choices separated by commas (e.g., Male,Female,Other).")),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which fields appear on the form.')),
                ('is_active', models.BooleanField(default=True, help_text='Include this field in the form?')),
            ],
            options={
                'verbose_name': 'Application Form Field',
                'verbose_name_plural': 'Application Form Fields',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=200)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Submission',
                'verbose_name_plural': 'Application Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.applicationformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='admissions.applicationsubmission')),
            ],
            options={
                'verbose_name': 'Submission Data',
                'verbose_name_plural': 'Submission Data',
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
