# Generated by Django 5.1.6 on 2025-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text (Single Line)'), ('textarea', 'Text Area (Multi Line)'), ('email', 'Email'), ('number', 'Number'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('date', 'Date'), ('file', 'File Upload'), ('image', 'Image Upload')], max_length=20),
        ),
    ]
