# Generated by Django 5.2 on 2025-04-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=210, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the program.')),
                ('duration', models.CharField(help_text='e.g., 3 Years, 6 Months', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this program currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programcategory')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
